### ISSUE TITLE
Toml definition crashing game

### ISSUE THREAD

**Issue by Ultimushadow** [ActuallySleeping/Building-Dimension#2]
Hey there, I was testing out this mod for a server I wanted to add it to, but I ran into a couple issues along the way
First off, the /creative command wouldn't work in my modpack, it's got hundreds of mods in there though so I'm still trying to figure out what's causing that. This entails a light pack of the optimization mods and QoL for mod testing, nothing that _should_ mess with things, and at first the game launched fine, the command works and the building dimension loaded properly and everything
Unfortunately, in my quest to figure out what was going on, after I launched the game, I closed it out to change my loaded mods, and then couldn't reload the game. When I delete the config, the game loads again, but when I do not, your code moves to line 25 of Configs.java and crashes because it doesn't have the Toml definition

I'm playing in 1.20.1, Fabric v0.14.22, with the 1.20.1-1.0.6 version of Building Dimension.
Log: [latest.log](https://github.com/ActuallySleeping/Building-Dimension/files/12596160/latest.log)
Crash Report: [crash-2023-09-13_04.53.58-client.txt](https://github.com/ActuallySleeping/Building-Dimension/files/12596173/crash-2023-09-13_04.53.58-client.txt)

I'm still trying to piece together why it didn't import correctly but I assume you will be able to catch it faster than me

**Comment by leclerc-leo** [comment]
Hello, thank you for your report, I'll look into it this afternoon. Honestly I never tested it with any other mods exept Create and the config is probably too poorly checked.

**Comment by Ultimushadow** [comment]
I can't tell if it's the Toml class import or the toml4j import that's not functioning here, thanks for looking into it!
On the topic of config, I'll be making a small list of suggestions in another report, I definitely love the utility of this mod though and will be using it once I can figure out the conflict the started this whole thing

**Comment by leclerc-leo** [comment]
After some research I was able to pinpoint the exact reason of the crash and managed to replicate the issue on my own.

I am currently working on a fix

**Comment by leclerc-leo** [comment]
I have republished the file at https://legacy.curseforge.com/minecraft/mc-mods/building-dimension/files/4750877

I have now tested it and should work fine, if the /creative command doesn't work please let me know

**Comment by Ultimushadow** [comment]
Perfect, I'll test it tonight, I really appreciate the quick response time! 👏🏻 
I'll try to figure out that command conflict, I've got a couple mods in mind for what it might be but there are about 300 of them so my intuition is the only timeframe there lol

**Comment by Ultimushadow** [comment]
Can confirm that the fix works and should be fine for anyone who had a previous version of the mod with the config issue 👌🏻 I'll be hunting that command issue next!

**Comment by leclerc-leo** [comment]
If you do see anything that could be the explanation send it and I'll try looking into it.
