### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by LordMaximus05** [ActuallySleeping/Building-Dimension#8]
Hi I am having an issue on my Fabric 1.20.1 server where everytime I try to tp to the creative world it crashes and says that it is missing the dimension Building_Dimension:Overworld and I have to be teleported back using a repeating command block. I have Fabric API and Fantasy Library installed as well as the Multiworld Mod. 

I have attached the latest log, hope you can figure this out. I really want a creative world to keep people on my server! Please let me know if you need more info or context.

[latest (4).log](https://github.com/leclerc-leo/Building-Dimension/files/13856488/latest.4.log)

**Comment by LordMaximus05** [comment]
additionally, I tried doing it in a singleplayer and it crashed me to desktop so it isn't a server issue.

**Comment by leclerc-leo** [comment]
Hello, thanks for opening an issue. I've looked a bit into the file and cant find the issue immediately.
I'll look more into it this week, I've never seen packet, is that the server log or single player log ? If it's single player, if you have the server only logs that could also help.

Are you using a premade modpack ? If so, I could download it to test more in depth.

**Comment by leclerc-leo** [comment]
Little follow up, Could you try removing ImmersivePortals.
If it works again, I'll try to integrate it to work.

**Comment by LordMaximus05** [comment]
Thanks for the response! I removed Immersive portals, and it worked! So, if it is possible to integrate that mod, that would be awesome! I am also having a new issue where every time I tp to the creative world and back (in single player) my advancements get reset. If you want to test the modpack it is a custom modpack but it was approved by CurseForge, so just search "SteamCraft - Train focus". You will have to add the Building Dimension mod since it is server-side only. Thank you again for responding so quickly!

Here are the singleplayer logs:
[latest.log](https://github.com/leclerc-leo/Building-Dimension/files/13861860/latest.log)

**Comment by leclerc-leo** [comment]
No problem, for the achievements It should give them back when going back I'll try to test it a bit more as giving Achievements is a bit hard and something might be broken.

**Comment by LordMaximus05** [comment]
Okay, after a bit more testing I do retain my advancements it just gives the popups every time. A tad annoying, but not the end of the world. I would rather have immersive portals be compatible :)

**Comment by leclerc-leo** [comment]
Yes i tried to patched it by turning the gamerule off but it seems like it's not working, might be due to the server-side only. I'll test it more.
For immersive portals I've looked a bit online and haven't found a quick fix but I hope it's not due to the server-side only or the fact I'm loading dimension just after the server started.

**Comment by LordMaximus05** [comment]
I wont be avaliable for a few hours, if you need to reach me you may contact me on discord "lordmaximus05". I seem to be having a lot of unique problems such as: I logged off in the creative world and lost my inventory lol (have replicated so not a one time issue) so I will do some more intensive testing tonight by removing mods and such so you don't have to do so much work!

**Comment by leclerc-leo** [comment]
Sure, I'll send you a request.
Also if you want to only include the mod for your server, you could do a server zip for example like : https://www.curseforge.com/minecraft/modpacks/create-astral/files/4729689
At the bottom of the page there is "Additional files" with the server zip, also useful if there are others server side mods.

**Comment by leclerc-leo** [comment]
A fix is comming in the next update and is currently working.
